### ISSUE TITLE
Build error on Ubuntu in EC_Camera

### ISSUE THREAD

**Issue by peterclemenko** [realXtend/tundra#553]
EC_Camera errors on build with the following error:

src/Core/OgreRenderingModule/EC_Camera.cpp: In member function ‘Ray EC_Camera::ViewportPointToRay(float, float) const’:
src/Core/OgreRenderingModule/EC_Camera.cpp:315:101: error: operands to ?: have different types ‘Ogre::Ray’ and ‘Ray’
src/Core/OgreRenderingModule/EC_Camera.cpp:316:1: warning: control reaches end of non-void function [-Wreturn-type]
make[2]: **\* [src/Core/OgreRenderingModule/CMakeFiles/OgreRenderingModule.dir/EC_Camera.o] Error 1

It appears to be caused by commit d4c7ab8175965da2b72ee5da064f8d1e581fb860
